name: Sync Mars Rover Data

on:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day at midnight
  workflow_dispatch: # Allows you to trigger it manually via a button click

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Requests
      run: pip install requests

    - name: Run Scrubbing Script
      run: python update_data.py

    - name: Commit and Push Clean Files
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add *.geojson
        git diff-index --quiet HEAD || git commit -m "Auto-update Mars Rover data"
        git push
